title: 欧雷流
tagline: 不走寻常路
description: 我叫欧雷，英文名 Ourai Lin，是一个出生于上世纪 80 年代的理想主义叛逆青年。喜欢日本，热爱咖啡，善于总结。这里有我对技术和语言的研究，也有对世界和生活的思考。目前从事前端工程师一职。

collections:
  pages:
    output: true
    permalink: /:path/
  sketches:
    output: true
    permalink: /:collection/:path/
  demos:
    output: true
    permalink: /:collection/:path/
  tutorials:
    output: true
    permalink: /:collection/:path/
  issues:
    output: true
    permalink: /:collection/:path/
  ja:
    output: true
    permalink: /:collection/:path/

# Handling Reading
exclude: 
  - .asset-cache
  - .sass-cache
  - node_modules
  - vendors
  - src
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - Gruntfile.coffee
  - bower.json
  - package.json
  - CNAME
  # - README.md
encoding: utf-8

# Plugins
gems:
  - jekyll-assets
  - jekyll-archives
  - jekyll-feed
  - jekyll-contentblocks
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll/tagging
  - jekyll-tagging-related_posts
  - jekyll_version_plugin

# Conversion
markdown: kramdown
highlighter: pygments

# Outputting
permalink: /posts/:title/
timezone: Asia/Shanghai

# YAML frontmatter
defaults:
  # 默认
  - scope:
      path: ""
    values:
      layout: default
  # 页面
  - scope:
      path: ""
      type: pages
    values:
      layout: page
  # 文章
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      css:
        - pages/post
      js:
        - initializers/time
      author:
        name: 欧雷
        email: ourairyu@gmail.com
        uri: http://ourai.github.io/
        slug: ourai
        twitter: ourairyu
      comments: true
  - scope:
      path: ""
      type: demos
    values:
      sitemap: false
  - scope:
      path: ""
      type: issues
    values:
      sitemap: false
  - scope:
      path: sketches/v1
      type: sketches
    values:
      layout: sketch/v1
      sitemap: false
  - scope:
      path: sketches/v2
      type: sketches
    values:
      layout: sketch/v2
      sitemap: false



# =====
# Plugin-specific configurations
# =====

# Jekyll Archives
# https://github.com/jekyll/jekyll-archives
jekyll-archives:
  enabled:
    - categories
    - tags
    - year
  layouts:
    category: archive/category
    tag: archive/tag
    year: archive/year
  permalinks:
    category: "/categories/:name/"
    tag: "/tags/:name/"
    year: "/archives/:year/"

# Jekyll Feed
feed:
  path: atom.xml
name: 欧雷流
author:
  name: 欧雷
  email: ourairyu@gmail.com
  uri: http://ourai.github.io/
  twitter: ourairyu
github:
  url: http://ourai.github.io
