encoding: utf-8

title: Developer Center
keywords: '欧雷,欧雷流,宅男的部屋,宅男部屋,宅男,ourai,ourairyu,developer,center,dev,network,front-end,web,网络开发,web开发,开发网络,开发中心'
tagline: The best site in the WORLD...?
hosted_on:
  name: GitHub
  url: https://github.com/
  desc: GitHub
powered_by:
  name: Jekyll
  url: http://jekyllrb.com/
  desc: Jekyll


url:
  root: http://dev.ourai.ws/
  asset: http://dev.ourai.ws/assets/
  # Pages
  article: http://dev.ourai.ws/articles/
  demo: http://dev.ourai.ws/demos/
  doc: http://dev.ourai.ws/docs/
  spec: http://dev.ourai.ws/specs/
  about: http://dev.ourai.ws/about/
  # Resource
  js: http://dev.ourai.ws/assets/javascripts/
  css: http://dev.ourai.ws/assets/stylesheets/
  img: http://dev.ourai.ws/assets/images/

author:
  name: 欧雷
  name_en: Ourai Lin
  avatar: http://www.gravatar.com/avatar/0565b1df14e0b4a1a9cdecb3f085cdba
  website: http://ourai.ws/
  profile: http://ourai.ws/

permalink: /posts/:title/
