title: 欧雷流
description: 不走寻常路

# Use for Atom feed
name: 欧雷流
author:
  name: 欧雷
  email: ourairyu@gmail.com
  uri: http://ourai.ws/
github:
  url: http://ourai.ws

collections:
  sketches:
    output: true
    permalink: /:collection/:path/
  demos:
    output: true
    permalink: /:collection/:path/
  tutorials:
    output: true
    permalink: /:collection/:path/
  issues:
    output: true
    permalink: /:collection/:path/
  ja:
    output: true
    permalink: /:collection/:path/

# Handling Reading
exclude: 
  - .sass-cache
  - node_modules
  - vendors
  - src
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - Gruntfile.coffee
  - bower.json
  - package.json
  # - README.md
encoding: utf-8

# Plugins
gems:
  - jekyll-archives
  - jekyll-feed
  - jekyll-slim
  - jemoji
  - octopress-minify-html

# Conversion
markdown: kramdown
# highlighter: false

# Backwards-compatibility
relative_permalinks: false

# Outputting
permalink: /posts/:title/
timezone: Asia/Shanghai

# YAML frontmatter
defaults:
  # Default
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: pages
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      layout_css:
        - share
        - pages/common
      layout_js:
        - pages/post
      author:
        name: 欧雷
        email: ourairyu@gmail.com
        uri: http://ourai.ws/
        slug: ourai
      comments: true
  - scope:
      path: sketches/v1
      type: sketches
    values:
      layout: sketch/v1
  - scope:
      path: sketches/v2
      type: sketches
    values:
      layout: sketch/v2



# =====
# Plugin-specific configurations
# =====

# Jekyll Archives
# https://github.com/jekyll/jekyll-archives
jekyll-archives:
  enabled:
    - categories
  layouts:
    category: category
  permalinks:
    category: "/categories/:name/"

# Jekyll Feed
feed:
  path: atom.xml

# Jekyll Slim
slim:
  pretty: true
  format: html5
