# Handling Reading
exclude: [".sass-cache", "node_modules", "src", "CNAME", "Gemfile", "Gemfile.lock", "Gruntfile.coffee", "bower.json", "package.json", "README.md"]
encoding: utf-8

# Plugins
gems:
  - jemoji

# Conversion
markdown: kramdown
# highlighter: false

# Backwards-compatibility
relative_permalinks: false

# Outputting
permalink: /posts/:title/
timezone: Asia/Shanghai

# YAML frontmatter
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      layout_type: "sandwich"
  - scope:
      path: ""
      type: "post"
    values:
      layout: "article"
      comments: true
