collections:
  pages:
    output: true
    permalink: /:collection/:path/
  projects:
    output: true
    permalink: /:collection/:path/
  demos:
    output: true
    permalink: /:collection/:path/
  tutorials:
    output: true
    permalink: /:collection/:path/
  issues:
    output: true
    permalink: /:collection/:path/

# Handling Reading
exclude: [".sass-cache", "node_modules", "src", "CNAME", "Gemfile", "Gemfile.lock", "Gruntfile.coffee", "bower.json", "package.json", "README.md"]
encoding: utf-8

# Plugins
gems:
  - jemoji

# Conversion
markdown: kramdown
# highlighter: false

# Backwards-compatibility
relative_permalinks: false

# Outputting
permalink: /posts/:title/
timezone: Asia/Shanghai

# YAML frontmatter
defaults:
  # Default
  - scope:
      path: ""
    values:
      layout: default
      layout_type: sandwich
  # Pages
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      template: page
  # Posts
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      template: article
      layout_css:
        - highlight
        - pages/article
      comments: true
  # Demos
  - scope:
      path: ""
      type: demos
    values:
      layout: demo
      template: demo
      layout_css:
        - highlight
      layout_js:
        - demo
      page_category: demo
  # Tutorials
  - scope:
      path: ""
      type: tutorials
    values:
      layout: page
      template: page
      page_category: tutorial
  # Issues
  - scope:
      path: ""
      type: issues
    values:
      layout: demo
      template: demo
      layout_css:
        - highlight
      layout_js:
        - demo
      page_category: demo
  # Tatami API
  - scope:
      path: "projects/tatami"
      type: projects
    values:
      layout: tatami
      template: tatami
      layout_css:
        - pages/tatami
      layout_js:
        - pages/doc
      project_name: Tatami
