# Global
encoding: utf-8
timezone: Asia/Shanghai
# pygments: false
markdown: kramdown
relative_permalinks: false
permalink: /posts/:title/

# YAML frontmatter
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      layout_type: "sandwich"
  - score:
      path: ""
      type: "post"
    values:
      layout: "article"
      comments: true
