title: 欧雷流

collections:
  re:
    output: true
    permalink: /:collection/:path/

# Handling Reading
exclude: 
  - .sass-cache
  - node_modules
  - vendors
  - src
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - Gruntfile.coffee
  - bower.json
  - package.json
  - README.md
encoding: utf-8

# Plugins
gems:
  - jemoji
  - jekyll-slim
  - octopress-minify-html

# Conversion
markdown: kramdown
# highlighter: false

# Backwards-compatibility
relative_permalinks: false

# Outputting
permalink: /posts/:title/
timezone: Asia/Shanghai

# YAML frontmatter
defaults:
  # Default
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: re/v1
      type: re
    values:
      layout: re/v1

# Jekyl Slim
slim:
  pretty: true
  format: html5

# Jekyll Assets
assets:
  js_compressor: uglifier
  css_compressor: sass
