# Global
encoding: utf-8
timezone: Asia/Shanghai
pygments: true
relative_permalinks: false
permalink: /:title/



# YAML frontmatter
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      layout_type: "sandwich"
  -
    score:
      path: ""
      type: "post"
    values:
      layout: "article"
      comments: true



url:
  root: http://dev.ourai.ws
  asset: assets
  # Pages
  article: articles
  demo: demos
  doc: docs
  spec: specs
  about: about
  # Resource
  js: assets/javascripts
  css: assets/stylesheets
  img: assets/images

# Site
title: "Ourai's Workstation"
keywords: "欧雷,欧雷流,宅男的部屋,宅男部屋,宅男,ourai,ourairyu,developer,center,dev,network,front-end,web,网络开发,web开发,开发网络,开发中心"
tagline: "The best site in the WORLD...?"
hosted_on:
  name: GitHub
  url: https://github.com/
  desc: GitHub
powered_by:
  name: Jekyll
  url: http://jekyllrb.com/
  desc: Jekyll
dependencies:
  -
    name: Jekyll
    url: http://jekyllrb.com/
    desc: "Jekyll is a simple, blog-aware, static site generator. It takes a template directory containing raw text files in various formats, runs it through Markdown (or Textile) and Liquid converters, and spits out a complete, ready-to-publish static website suitable for serving with your favorite web server."
    image: jekyll.png
  -
    name: GitHub
    url: https://github.com/
    desc: "GitHub is the best place to share code with friends, co-workers, classmates, and complete strangers. Over four million people use GitHub to build amazing things together."
    image: github.png
  -
    name: Disqus
    url: http://disqus.com/
    desc: "Disqus is a free service that enables great online communities. As the web’s most popular discussion system, Disqus is used by millions of websites that cover pretty much any topic imaginable. Its magic is in connecting people to stuff worth talking about."
    image: disqus.png

author:
  name: 欧雷
  name_en: Ourai Lin
  avatar: http://www.gravatar.com/avatar/0565b1df14e0b4a1a9cdecb3f085cdba
  website: http://ourai.ws/
  profile: http://ourai.ws/
  desc: 欧雷流
