(function( window ) {

var data = {
	// 产品目录
	catetories: [{
		name: "合成纤维吊装带",
		children: ["柔性吊装带", "迪尼玛吊装带", "扁平吊装带", "高强酸洗吊装带", "吊装带成套索具", "收紧器", "牵引带"]
	}, {
		name: "尼龙绳吊装系列",
		children: ["常用尼龙绳", "船用缆绳"]
	}, {
		name: "钢丝绳吊装系列",
		children: ["插编钢丝绳索具", "压制钢丝绳索具", "无接头钢丝绳吊具", "浇铸钢丝绳索具", "复合钢丝绳索具", "特种钢丝绳索具"]
	}, "链条索具", "索具配件", "钢板起重钳系列", "永磁吸盘", "冶金吊夹具系列", "平衡吊梁系列", {
		name: "安全防护系列",
		children: ["软梯", "安全网 吊网", "安全带", "防坠器 自锁器"]
	}, "三动工具系列"],
	
	// 产品
	products: {
		"cat_1": {
			"cat_1.1": {
				list:[{ id: "SW001", name: "1T柔性环形吊带" },
				      { id: "SW002", name: "2T柔性环形吊带" },
				      { id: "SW003", name: "3T柔性环形吊带" },
				      { id: "SW004", name: "5T柔性环形吊带" },
				      { id: "SW005", name: "8T柔性环形吊带" },
				      { id: "SW006", name: "12T柔性环形吊带" },
				      { id: "SW007", name: "两头扣圆状吊带" },
				      { id: "SW008", name: "两头扣圆装吊带" },
				      { id: "SW010", name: "柔性环形吊带" },
				      { id: "SW011", name: "防护性柔性吊带" },
				      { id: "SW012", name: "两头扣柔性吊带"}]
			},
			"cat_1.2": {
				list: [{ id: "SW013", name: "迪尼玛环形柔性吊带" },
				       { id: "SW014", name: "迪尼玛两头扣柔性吊装带" },
				       { id: "SW015", name: "防火环形柔性吊装带" },
				       { id: "SW016", name: "防火两头扣柔性吊装带" }]
			},
			"cat_1.3": {
				list: [{ id: "SW017", name: "两头扣扁平吊装带" },
				       { id: "SW018", name: "加厚两头扣扁平吊装带" },
				       { id: "SW019", name: "环型扁平吊装带" },
				       { id: "SW020", name: "加厚环形扁平吊装带" },
				       { id: "SW021", name: "宽体型扁平吊装带" },
				       { id: "SW022", name: "聚酯防割扁吊带" },
				       { id: "SW023", name: "护套吊带" },
				       { id: "SW024", name: "石油管道专用吊带" },
				       { id: "SW025", name: "专用玻璃吊带" }]
			},
			"cat_1.4": {
				list: [{ id: "SW026", name: "白色高强酸洗吊带" },
				       { id: "SW027", name: "变色棉纶高强吊带" },
				       { id: "SW028", name: "两头扣高强酸洗吊带" }]
			},
			"cat_1.5": {
				list: [{ id: "SW030", name: "单组合吊带" },
				       { id: "SW031", name: "二组合吊带" },
				       { id: "SW032", name: "三组合吊带" },
				       { id: "SW033", name: "四组合吊带" }]
			},
			"cat_1.6": {
				list: [{ id: "SW034", name: "" },
				       { id: "SW035", name: "" },
				       { id: "SW036", name: "" },
				       { id: "SW037", name: "" }]
			},
			"cat_1.7": {
				list: [{ id: "SW045", name: "" },
				       { id: "SW046", name: "" },
				       { id: "SW047", name: "" },
				       { id: "SW048", name: "" },
				       { id: "SW049", name: "" },
				       { id: "SW050", name: "" },
				       { id: "SW051", name: "" },
				       { id: "SW052", name: "" },
				       { id: "SW053", name: "" }]
			}
		},
		"cat_2": {
			"cat_2.1": {
				list: [{ id: "SW054", name: "三股绞制绳" },
				       { id: "SW055", name: "三股绞制绳" },
				       { id: "SW056", name: "八股绞制绳" },
				       { id: "SW057", name: "高空清洗安全绳" },
				       { id: "SW058", name: "新型专用清洗板" },
				       { id: "SW059", name: "钢丝安全绳" },
				       { id: "SW060", name: "船舶缆绳" },
				       { id: "SW061", name: "船舶缆绳" },
				       { id: "SW062", name: "启动拉绳" },
				       { id: "SW063", name: "引纸绳" },
				       { id: "SW064", name: "蚕丝绝缘绳" },
				       { id: "SW065", name: "聚乙烯绳" },
				       { id: "SW066", name: "花色抢险绳" },
				       { id: "SW067", name: "高压线路牵引绳" },
				       { id: "SW068", name: "船用迪尼玛绳" },
				       { id: "SW069", name: "迪尼玛花绳" },
				       { id: "SW071", name: "两叉尼龙绳组合吊具" },
				       { id: "SW072", name: "三叉尼龙绳组合吊具" },
				       { id: "SW073", name: "四叉尼龙绳组合吊具" },
				       { id: "SW074", name: "两头扣尼龙吊绳" },
				       { id: "SW075", name: "双扣尼龙吊带" },
				       { id: "SW076", name: "环型尼龙吊绳" },
				       { id: "SW077", name: "双叉尼龙吊绳" },
				       { id: "SW078", name: "四叉尼龙吊绳" },
				       { id: "SW079", name: "两叉组合尼龙吊绳" },
				       { id: "SWG103", name: "空心引纸绳" },
				       { id: "SWG104", name: "加光染色引纸绳" },
				       { id: "SWG105", name: "加光加亮引纸绳" },
				       { id: "SWG106", name: "引纸带" }]
			},
			"cat_2.2": {
				list: [{ id: "SW080", name: "三股绳" },
				       { id: "SW081", name: "六股绳" },
				       { id: "SW082", name: "八股绳" },
				       { id: "SW083", name: "十二股绳" }]
			}
		},
		"cat_3": {
			"cat_3.1": {
				list: [{ id: "SW105", name: "插编钢丝绳索具" },
				       { id: "SW106", name: "压胶插编钢丝绳" },
				       { id: "SW107", name: "无油插编钢丝绳" }]
			},
			"cat_3.2": {
				list: [{ id: "SW108", name: "压制钢丝绳索具" },
				       { id: "SW109", name: "压制钢丝绳" },
				       { id: "SW110", name: "无油压制钢丝绳" },
				       { id: "SW111", name: "特种不锈钢压制钢丝绳" },
				       { id: "SW115", name: "单环四叉复合钢丝绳" },
				       { id: "SW116", name: "尼龙复合钢丝绳" },
				       { id: "SW117", name: "橡胶复合压制钢丝绳" },
				       { id: "SW118", name: "压制复合钢丝绳" },
				       { id: "SW119", name: "橡胶钢丝绳吊带" },
				       { id: "SW120", name: "特制复合钢丝绳" },
				       { id: "SW121", name: "三叉压胶钢丝绳吊具" },
				       { id: "SW122", name: "橡胶钢丝绳索具" },
				       { id: "SW123", name: "四叉橡胶钢丝绳索具" },
				       { id: "SW124", name: "外包尼龙钢丝绳成套索具" }]
			},
			"cat_3.3": {
				list: [{ id: "SW112", name: "无接头钢丝绳" }]
			},
			"cat_3.4": {
				list: [{ id: "SW113", name: "开式浇铸钢丝绳索具" },
				       { id: "SW114", name: "闭式浇铸钢丝绳索具" }]
			},
			"cat_3.5": {
				list: [{ id: "SW125", name: "注塑水平绳压制索具" },
				       { id: "SW126", name: "注塑水平绳" },
				       { id: "SWG135", name: "不锈钢钢丝绳" }]
			},
			"cat_3.6": {
				list: [{ id: "SW127", name: "电缆网套" },
				       { id: "SW128", name: "电缆网套" },
				       { id: "SW129", name: "九股钢丝绳索具" },
				       { id: "SW130", name: "钢丝编缆" },
				       { id: "SW131", name: "特制钢丝绳吊索" }]
			}
		},
		"cat_4": {
			list: [{ id: "SW132", name: "S(6)级单腿链条索具" },
			       { id: "SW133", name: "S(6)级双腿链条索具" },
			       { id: "SW134", name: "组装型T(8)级单腿链条索具" },
			       { id: "SW135", name: "组装型T(8)级双腿链条索具" },
			       { id: "SW136", name: "S(6)级三肢链条索具" },
			       { id: "SW137", name: "S(6)级四肢链条索具" },
			       { id: "SW138", name: "组装型T(8)级三肢链条索具" },
			       { id: "SW139", name: "组装型T(8)级四肢链条索具" },
			       { id: "SW140", name: "S(6)级单肢环形链条索具" },
			       { id: "SW141", name: "S(6)级双肢环形链条索具" },
			       { id: "SW142", name: "T(8)级环形链条索具" },
			       { id: "SW143", name: "T(8)级环形链条捆绑索具" },
			       { id: "SW144", name: "钢坯专用索具" },
			       { id: "SW145", name: "单腿组合" },
			       { id: "SW146", name: "双腿组合" },
			       { id: "SW147", name: "三腿组合" },
			       { id: "SW148", name: "四腿组合" }]
		},
		"cat_5": {
			list: [{ id: "SW149", name: "旋转吊钩" },
			       { id: "SW150", name: "环眼滑钩" },
			       { id: "SW151", name: "美式货钩" },
			       { id: "SW152", name: "S钩" },
			       { id: "SW153", name: "眼形货钩" },
			       { id: "SW154", name: "鼻形钩" },
			       { id: "SW155", name: "眼形货钩（带保险卡）" },
			       { id: "SW156", name: "直柄吊钩" },
			       { id: "SW157", name: "梨形环" },
			       { id: "SW158", name: "圆吊环" },
			       { id: "SW159", name: "羊角滑钩（带保险卡）" },
			       { id: "SW160", name: "羊角吊钩" },
			       { id: "SW161", name: "长吊环（焊接）" },
			       { id: "SW162", name: "羊角抓钩" },
			       { id: "SW163", name: "长吊环（锻造）" },
			       { id: "SW164", name: "组合吊环" },
			       { id: "SW165", name: "西德套环" },
			       { id: "SW166", name: "吊环螺钉" },
			       { id: "SW167", name: "美标弓形卸扣" },
			       { id: "SW168", name: "美标D型卸扣" },
			       { id: "SW169", name: "重型套环" },
			       { id: "SW170", name: "钢线绳楔形接头" },
			       { id: "SW171", name: "浇铸用接头（闭式）" },
			       { id: "SW172", name: "浇铸用接头（开式）" },
			       { id: "SW173", name: "钢丝绳护角" },
			       { id: "SW174", name: "吊带护角" },
			       { id: "SW175", name: "膜式翻身吊钩" },
			       { id: "SW176", name: "A型钢丝绳夹" },
			       { id: "SW177", name: "链条调节器" },
			       { id: "SW178", name: "链条连接器" },
			       { id: "SW179", name: "弯孔钩" },
			       { id: "SW180", name: "旋转安全钩" },
			       { id: "SW181", name: "安全钩" },
			       { id: "SW182", name: "弓形卸扣" },
			       { id: "SW183", name: "D型卸扣" },
			       { id: "SW184", name: "吊点" },
			       { id: "SW185", name: "羊角环" },
			       { id: "SW186", name: "钢管吊钳" },
			       { id: "SW187", name: "欧米格卸扣" },
			       { id: "SW188", name: "欧式圆环套" },
			       { id: "SW189", name: "H扣" },
			       { id: "SW190", name: "G80旋转环" },
			       { id: "SW191", name: "大开口钩" },
			       { id: "SW192", name: "异型眼型钩" },
			       { id: "SW193", name: "特制单钩" },
			       { id: "SW194", name: "特制双钩" },
			       { id: "SW195", name: "J型钩" },
			       { id: "SW196", name: "链条连接扣" },
			       { id: "SW197", name: "蝴蝶吊钩" },
			       { id: "SW198", name: "油田旋转吊钩" },
			       { id: "SW199", name: "旋转吊环" },
			       { id: "SW200", name: "中型滑车" },
			       { id: "SW201", name: "重型滑车" },
			       { id: "SW202", name: "花兰螺丝（美式OO型）" },
			       { id: "SW203", name: "花兰螺丝（美式CO型）" },
			       { id: "SW204", name: "花兰螺丝（美式UU型）" },
			       { id: "SW205", name: "花兰螺丝（美式DO型）" },
			       { id: "SW206", name: "特殊型号花兰螺丝" },
			       { id: "SWG167", name: "重型D型卸扣" },
			       { id: "SWG168", name: "高强度卸扣" },
			       { id: "SWG169", name: "高强度卸扣" },
			       { id: "SWG170", name: "防转套" },
			       { id: "SWG171", name: "梨形绳套" },
			       { id: "SWG172", name: "C型快速卸扣" },
			       { id: "SWG173", name: "万向垂重钩" }]
		},
		"cat_6": {
			list: [{ id: "SW207", name: "横吊钢板起重钳" },
			       { id: "SW208", name: "竖吊钢板起重钳" },
			       { id: "SW209", name: "翻转钳（DFQ）" },
			       { id: "SW210", name: "油桶钳（YQC）" },
			       { id: "SW211", name: "油桶钳（DYQ）" },
			       { id: "SW212", name: "L型钢板起重钳" },
			       { id: "SW213", name: "单板起重钳" },
			       { id: "SW214", name: "双板起重钳" },
			       { id: "SW215", name: "层叠钢板起重钳（PDK）" },
			       { id: "SW216", name: "H型钢吊钳" },
			       { id: "SW217", name: "SL型模锻简易吊卡" },
			       { id: "SW218", name: "DYKQ型圆钢用夹钳" },
			       { id: "SW219", name: "HQC型竖吊用夹钳" },
			       { id: "SW220", name: "HLC型铸钢起重吊钩" }]
		},
		"cat_7": {
			list: [{ id: "SW221", name: "永磁吸盘" },
			       { id: "SW222", name: "强磁起重机" }]
		},
		"cat_8": {
			list: [{ id: "SW223", name: "方坯吊钳" },
			       { id: "SW224", name: "自动闭合带钢卷夹钳" },
			       { id: "SW225", name: "钢锭吊具" },
			       { id: "SW226", name: "圆钢吊具" },
			       { id: "SW227", name: "圆钢吊具" },
			       { id: "SW228", name: "钢板夹具" },
			       { id: "SW229", name: "竖吊卷板吊具" },
			       { id: "SW230", name: "竖吊卷板吊具" },
			       { id: "SW231", name: "C型-A卷板吊具" },
			       { id: "SW232", name: "C型-B卷板吊具" },
			       { id: "SW233", name: "双吊环式" },
			       { id: "SW234", name: "套筒式" },
			       { id: "SW235", name: "电动卧卷夹钳" },
			       { id: "SW235-1", name: "电动卧卷夹钳" },
			       { id: "SW236", name: "JT型夹持器" },
			       { id: "SW237", name: "单轧辊吊具" },
			       { id: "SW238", name: "双轧辊吊具" },
			       { id: "SW239", name: "双吊耳板还吊具" },
			       { id: "SW240", name: "卷纸吊具" },
			       { id: "SW241", name: "双钩C型卷板吊具" },
			       { id: "SW242", name: "钢锭吊具" },
			       { id: "SW243", name: "中间罐吊具" },
			       { id: "SWG174", name: "电动平移式板坯夹钳" },
			       { id: "SWG175", name: "机械杠杆式板坯夹钳" },
			       { id: "SWG176", name: "液压连杆式板垛吊具" },
			       { id: "SWG177", name: "自闭合立卷夹钳" },
			       { id: "SWG178", name: "锭铁夹具" },
			       { id: "SWG179-1", name: "自闭合夹钳1" },
			       { id: "SWG179-2", name: "自闭合夹钳2" },
			       { id: "SWG180", name: "全封闭横轴式旋转吊钩" },
			       { id: "SWG181", name: "全封闭箱形式旋转吊钩" },
			       { id: "SWG182", name: "梁式大吨位旋转吊钩" },
			       { id: "SWG183", name: "半封闭吊钩组" },
			       { id: "SWG184", name: "钢桶夹抱器" },
			       { id: "SWG185", name: "多用汽车吊架" },
			       { id: "SWG186", name: "纸卷翻卷夹钳" },
			       { id: "SWG187", name: "中心立卷夹钳" },
			       { id: "SWG188", name: "电动平移式机械保护卧卷夹钳" },
			       { id: "SWG189", name: "卧卷夹钳" },
			       { id: "SWG190", name: "双边立卷夹钳" },
			       { id: "SWG191", name: "液压连杆卧卷夹钳" },
			       { id: "SWG192", name: "机械连杆卧卷夹钳" },
			       { id: "SWG193", name: "电动杠杆式板坯夹钳" },
			       { id: "SWG196", name: "手动平移式板垛吊具" },
			       { id: "SWG198", name: "各种吨位的抓斗" },
			       { id: "SWG199", name: "各种轧辊专业吊具" },
			       { id: "SWG200", name: "炉盖三爪吊具" },
			       { id: "SWG205-1", name: "各种联合C型铲齿吊具1" },
			       { id: "SWG205-2", name: "各种联合C型铲齿吊具2" },
			       { id: "SWG206", name: "型钢夹具" },
			       { id: "SWG207", name: "钢轨夹具" },
			       { id: "SWG208", name: "各种棒材类夹具" },
			       { id: "SWG209", name: "各种盘卷类吊夹具（内侧型）" },
			       { id: "SWG210", name: "各种盘卷类吊夹具（外侧型）" },
			       { id: "SWG211", name: "各种木材类吊夹具" },
			       { id: "SWG212", name: "伸缩式板材夹具" },
			       { id: "SWG213", name: "外侧夹取的夹具" },
			       { id: "SWG215", name: "纸卷夹具" },
			       { id: "SWG221", name: "钢卷升降梁" }]
		},
		"cat_9": {
			list: [{ id: "SW244", name: "HLA横梁系列" },
			       { id: "SW245", name: "HLB横梁系列" },
			       { id: "SW246", name: "起吊横梁" },
			       { id: "SW247", name: "铁路救援吊具" },
			       { id: "SW248", name: "HLC横梁系列" },
			       { id: "SW249", name: "平衡吊梁" },
			       { id: "SW250", name: "平衡吊梁" },
			       { id: "SW251", name: "HLD横梁系列" },
			       { id: "SW252", name: "平衡吊梁" },
			       { id: "SW253", name: "组合吊梁" },
			       { id: "SW254", name: "组合吊梁" },
			       { id: "SW255", name: "组合吊梁" },
			       { id: "SW256", name: "500T吊排" }]
		},
		"cat_10": {
			"cat_10.1": {
				list: [{ id: "SW257", name: "绝缘软梯（圆管）" },
				       { id: "SW258", name: "绝缘软梯（方管）" },
				       { id: "SW259", name: "木质软梯" },
				       { id: "SW260", name: "钢绳消防软梯" },
				       { id: "SW261", name: "钢丝绳软梯" },
				       { id: "SW262", name: "吊带软梯" },
				       { id: "SW263", name: "蚕丝绝缘软梯" },
				       { id: "SW264", name: "防潮合成纤维软梯" }]
			},
			"cat_10.2": {
				list: [{ id: "SW265", name: "锦纶扁带吊网" },
				       { id: "SW266", name: "钢丝绳吊网（6×37）" },
				       { id: "SW267", name: "聚乙烯绞制绳吊网（尼龙）" },
				       { id: "SW268", name: "电力滑线网" },
				       { id: "SW269", name: "带电跨越网" },
				       { id: "SW270", name: "吊带吊网" },
				       { id: "SW271", name: "尼龙吊网" },
				       { id: "SW272", name: "锦纶安全网" },
				       { id: "SW273", name: "涤纶安全网" },
				       { id: "SW274", name: "密目安全网（含阻燃）" },
				       { id: "SW275", name: "阻燃安全网" },
				       { id: "SW276", name: "无结安全网" },
				       { id: "SW277", name: "围栏防护网" },
				       { id: "SW278", name: "安全三角旗" },
				       { id: "SW279", name: "安全警示带" }]
			},
			"cat_10.3": {
				list: [{ id: "SW279", name: "安全带结构" },
				       { id: "SW280", name: "连结绳结构" },
				       { id: "SW281", name: "欧式安全带1" },
				       { id: "SW282", name: "欧式安全带2" },
				       { id: "SW283", name: "欧式安全带3" },
				       { id: "SW284", name: "欧式安全带4" },
				       { id: "SW285", name: "欧式安全带5" },
				       { id: "SW286", name: "架工安全带1" },
				       { id: "SW287", name: "架工安全带2" },
				       { id: "SW288", name: "单腰安全带" },
				       { id: "SW289", name: "单腰速差式安全带" },
				       { id: "SW290", name: "双背速差式安全带" },
				       { id: "SW291", name: "电工单保险安全带" },
				       { id: "SW292", name: "电工单保险安全带" },
				       { id: "SW293", name: "电工双保险安全带" },
				       { id: "SW294", name: "垂直攀登专用带" },
				       { id: "SW295", name: "新型登高板" },
				       { id: "SW296", name: "欧式安全带6" },
				       { id: "SW297", name: "欧式电工安全带1" },
				       { id: "SW298", name: "欧式电工安全带2" },
				       { id: "SW299", name: "欧式护腰带" }]
			},
			"cat_10.4": {
				list: [{ id: "SW300", name: "速差式自控防坠器" },
				       { id: "SW301", name: "速差式自控防坠器" },
				       { id: "SW302", name: "速差式自控防坠器" },
				       { id: "SW303", name: "攀登自锁器" },
				       { id: "SW304", name: "水平滑动器" },
				       { id: "SW305", name: "手抓器" },
				       { id: "SW306", name: "绳索式防坠器" },
				       { id: "SW307", name: "围杆绳调节器" }]
			}
		},
		"cat_11": {
			list: [{ id: "SW315", name: "COY脚踏式油桶搬运车" },
			       { id: "SW316", name: "COT型可倾式油桶装卸车" },
			       { id: "SW317", name: "CTY手动液压装卸叉车" },
			       { id: "SW318", name: "移运器" },
			       { id: "SW319", name: "地下电缆滑车" },
			       { id: "SW320", name: "滑车" },
			       { id: "SW321", name: "轴承加热器" },
			       { id: "SW322", name: "铝合金滑车" },
			       { id: "SW323", name: "花兰拉泵" },
			       { id: "SW324", name: "液压拉泵" },
			       { id: "SW325", name: "机动绞磨" },
			       { id: "SW326", name: "切排机" },
			       { id: "SW327", name: "剪叉式平台可移升降机" },
			       { id: "SW328", name: "铝合金高空作业平台" },
			       { id: "SW329", name: "手动液压升降机" },
			       { id: "SW330", name: "电动液压升降机" },
			       { id: "SW331", name: "DYZ系列整体式拔轮器" },
			       { id: "SW332", name: "DYF系列分体式拔轮器" },
			       { id: "SW333", name: "小车式升降拉马" },
			       { id: "SW335", name: "QL-II型" },
			       { id: "SW336", name: "QL-III型" },
			       { id: "SW337", name: "QL-I型" },
			       { id: "SW338", name: "液压钢丝绳切断机" },
			       { id: "SW339", name: "分离式钢丝绳切断器" },
			       { id: "SW340", name: "YWC型、SYW型4D液压弯管机系列" },
			       { id: "SW341", name: "电动液压弯管机" },
			       { id: "SW342", name: "分体式液压螺帽切开器" },
			       { id: "SW343", name: "螺母劈开器" },
			       { id: "SW344", name: "中空式液压扳手" },
			       { id: "SW345", name: "手动试压泵" },
			       { id: "SW346", name: "钢丝绳压套机" },
			       { id: "SW347", name: "双速液压钳" },
			       { id: "SW348", name: "盘根工具" },
			       { id: "SW349", name: "断头螺丝取出器" },
			       { id: "SW350", name: "手拉葫芦" },
			       { id: "SW351", name: "手扳葫芦" },
			       { id: "SW352", name: "TP型单型轨行车" },
			       { id: "SW353", name: "TG型单型轨行车" },
			       { id: "SW354", name: "电动葫芦" },
			       { id: "SW355", name: "轻型手扳葫芦" }]
		}
	}
};
	
window.SITE_DATA = data;
	
})( window );